### ISSUE TITLE
ar language

### ISSUE THREAD

**Issue by x3was** [Xxpromw3mtxX/lfKevlar#4]
i will make ar locals

**Comment by Xxpromw3mtxX** [comment]
nice! whenever you’re ready ask for a pull request or just put them here :)

**Comment by x3was** [comment]
Locales ['ar'] = {
    ['already_equipped'] = 'لديك بالفعل درع مجهز',
    ['light_equip'] = 'لقد قمت بلبس الدرع الخفيف',
    ['medium_equip'] = 'لقد قمت بلبس الدرع المتوسط',
    ['heavy_equip'] = 'لقد قمت بلبس الدرع الثقيل',
}

**Comment by Xxpromw3mtxX** [comment]
Implemented! Thank you :D
